id = "dark-void"
name = "Dark Void"
version = "0.0.1"
schema_version = 1
authors = ["arun-murali0"]
description = "Dark Void – high contrast warm dark theme for Zed."
repository = "https://github.com/arun-murali0/dark-void"
